include: package:flutter_lints/flutter.yaml
# FlutterのLintルールを使用する
# https://dart.dev/tools/linter-rules
linter:
  
  rules:
    - avoid_print: false # コンソールに出力するのはOK
    - prefer_single_quotes: true # シングルクオーテーションを使用する
    - prefer_const_constructors: true # constコンストラクタを使用する
    - prefer_const_literals_to_create_immutables: true # constリテラルを使用する
    - prefer_const_constructors_in_immutables: true # constコンストラクタを使用する
    - prefer_const_constructors_in_widgets: true # constコンストラクタを使用する
    - prefer_const_constructors_in_stateless_widgets: true # constコンストラクタを使用する
    - prefer_const_constructors_in_stateful_widgets: true # constコンストラクタを使用する
